[tool.poetry]
name = "spanish_translator"
version = "0.0.0"
description = "cli to translate to spanish"
authors = ["Brian White <brian@thirdember.com>"]
readme = "README.md"
packages = [{include = "spanish_translator"}]

[tool.poetry.dependencies]
python = "^3.10"
deep-translator = "^1.10.0"
num2words = "^0.5.12"
cloup = "^2.0.0.post1"

[tool.poetry.scripts]
spanish_translator = "spanish_translator.cli:run"

[tool.poetry.dev-dependencies]
flake8 = "^6.0.0"
black = "^23.1.0"

[tool.poetry-dynamic-versioning]
enable = true

[build-system]
requires = ["poetry-core", "poetry-dynamic-versioning"]
build-backend = "poetry.core.masonry.api"
# build-backend = "poetry_dynamic_versioning.backend"
